addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'DROP DATABASE IF EXISTS travis_ci_test;' -U postgres
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
dist: xenial
language: ruby
rvm:
  - 2.6.5
script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec
