sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.25.5

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_script:
  - docker-compose -f spec/docker-compose.yml up -d --build
  - cp config/database.yml.travis config/database.yml
  - psql -c 'DROP DATABASE IF EXISTS travis_ci_test;' -U postgres
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - |
    while ! docker exec -it spec_mysql8_1 mysql -u root --password=$TEST_DB_PASSWORD -e "status;"> /dev/null 2>&1; do
      echo 'Waiting for mysql8...'
      sleep 1;
    done;
  - docker exec -it spec_mysql8_1 mysqld --verbose --help | grep bind-address
  - docker exec -it spec_mysql8_1 mysql -u root --password=$TEST_DB_PASSWORD -e "show variables where Variable_name like 'have_ssl';"
  - docker exec -it spec_mysql8_1 mysql -u root --password=$TEST_DB_PASSWORD -e "status;"
dist: xenial
language: ruby
rvm:
  - 2.6.5
script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec

after_script:
  - docker-compose -f spec/docker-compose.yml down